apiVersion: apps/v1
kind: Deployment
metadata:
  name: arundeployment
  labels:
    app: aruv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: aruv
  template:
    metadata:
      labels:
        app: aruv
    spec:
      containers:
      - name: aruv
        image: arunvel1988/appv2
        ports:
        - containerPort: 8000

